### PR TITLE
added convar for trace mask

### PR DESCRIPTION
**Pull request by EntranceJew**
ideally to set it to `MASK_PLAYERSOLID` to prevent getting out of bounds

### CODE REVIEW

**Comment by doodlezucc** [comment]
Hello there, thanks so much for your PR! Although the changes look good, I noticed a problem when testing this. Apparently there's a conversion error in `ConVar:GetInt()` which may produce a slighty wrong number, resulting in an invalid mask:

image

This only seems to happen with larger numbers. The print logs above were made with the following lines:

```lua
print("Con Var (string) = " .. GetConVar("portalmod_shot_mask"):GetString())
print("Con Var (float)  = " .. GetConVar("portalmod_shot_mask"):GetFloat())
print("Con Var (int)    = " .. GetConVar("portalmod_shot_mask"):GetInt())
```

I really can't explain why this conversion error might occur. Anyway, by using Lua's builtin `tonumber()` function, we seem to be able to get around it:

image

Can you push another commit with the following changes? Cheers!

```lua
local function TraceHit(gun)
    local owner = gun:GetOwner()

    if owner ~= NULL and owner:IsPlayer() then
        maskString = GetConVar("portalmod_shot_mask"):GetString()

        return PortalTrace({
            start = owner:EyePos(),
            endpos = owner:EyePos() + (owner:EyeAngles():Forward()) * 30000,
            mask = tonumber(maskString)
        })
    else
        return PortalTrace({
            start = gun:GetPos(),
            endpos = gun:GetPos() + gun:GetAngles():Forward() * 30000,
        })
    end
end
```

**Comment by doodlezucc** [comment]
LGTM :)

**Comment by EntranceJew** [comment]
Amazing catch, I suspected as much when I ran `tostring()` on the mask itself, but I was hoping that the coercion behind GetInt/GetFloat would handle this on their end, maybe they don't survive a round trip.

**Comment by doodlezucc** [comment]
I'll try releasing this change as an update to the Steam workshop later, stay tuned. :shipit:

**Comment by Kefta** [comment]
This is indeed a bug in GMod and probably every EP2 (and prior) branch Source game. I don't know about any branches past that but it might be there too. The problem method is here: https://github.com/VSES/SourceEngine2007/blob/master/src_main/tier1/convar.cpp#L750 but there are other improper casts that might lead to more bugs in some of the Lua bindings of the Get/Sets if not engine code itself. I have mentioned this in Discord and am working on a functional rewrite of convar.h/cpp that will remedy these bugs (as well as adding Get/SetDouble support for Lua).

**Comment by doodlezucc** [comment]
That's really interesting, thanks for your insight and for pointing out the source of this bug.

**Pull request merged**
